# GApps dependencies
PRODUCT_COPY_FILES += \
    vendor/google/gapps/proprietary/system/addon.d/70-gapps.sh:system/addon.d/70-gapps.sh \
    vendor/google/gapps/proprietary/system/etc/g.prop:system/etc/g.prop \
    vendor/google/gapps/proprietary/system/etc/permissions/com.google.android.maps.xml:system/etc/permissions/com.google.android.maps.xml \
    vendor/google/gapps/proprietary/system/etc/permissions/com.google.android.media.effects.xml:system/etc/permissions/com.google.android.media.effects.xml \
    vendor/google/gapps/proprietary/system/etc/permissions/com.google.widevine.software.drm.xml:system/etc/permissions/com.google.widevine.software.drm.xml \
    vendor/google/gapps/proprietary/system/etc/permissions/features.xml:system/etc/permissions/features.xml \
    vendor/google/gapps/proprietary/system/etc/preferred-apps/google.xml:system/etc/preferred-apps/google.xml \
    vendor/google/gapps/proprietary/system/framework/com.google.android.maps.jar:system/framework/com.google.android.maps.jar \
    vendor/google/gapps/proprietary/system/framework/com.google.android.media.effects.jar:system/framework/com.google.android.media.effects.jar \
    vendor/google/gapps/proprietary/system/framework/com.google.widevine.software.drm.jar:system/framework/com.google.widevine.software.drm.jar \
    vendor/google/gapps/proprietary/system/lib/libAppDataSearch.so:system/lib/libAppDataSearch.so \
    vendor/google/gapps/proprietary/system/lib/libdocscanner_image-v7a.so:system/lib/libdocscanner_image-v7a.so \
    vendor/google/gapps/proprietary/system/lib/libdocsimageutils.so:system/lib/libdocsimageutils.so \
    vendor/google/gapps/proprietary/system/lib/libearthandroid.so:system/lib/libearthandroid.so \
    vendor/google/gapps/proprietary/system/lib/libearthmobile.so:system/lib/libearthmobile.so \
    vendor/google/gapps/proprietary/system/lib/libfacetracker.so:system/lib/libfacetracker.so \
    vendor/google/gapps/proprietary/system/lib/libfilterframework_jni.so:system/lib/libfilterframework_jni.so \
    vendor/google/gapps/proprietary/system/lib/libfilterpack_facedetect.so:system/lib/libfilterpack_facedetect.so \
    vendor/google/gapps/proprietary/system/lib/libfrsdk.so:system/lib/libfrsdk.so \
    vendor/google/gapps/proprietary/system/lib/libgames_rtmp_jni.so:system/lib/libgames_rtmp_jni.so \
    vendor/google/gapps/proprietary/system/lib/libgoogle_recognizer_jni_l.so:system/lib/libgoogle_recognizer_jni_l.so \
    vendor/google/gapps/proprietary/system/lib/libjni_eglfence.so:system/lib/libjni_eglfence.so \
    vendor/google/gapps/proprietary/system/lib/libjni_filtershow_filters.so:system/lib/libjni_filtershow_filters.so \
    vendor/google/gapps/proprietary/system/lib/libjni_latinimegoogle.so:system/lib/libjni_latinimegoogle.so \
    vendor/google/gapps/proprietary/system/lib/libjni_latinime.so:system/lib/libjni_latinime.so \
    vendor/google/gapps/proprietary/system/lib/libjni_t13n_shared_engine.so:system/lib/libjni_t13n_shared_engine.so \
    vendor/google/gapps/proprietary/system/lib/liblinearalloc.so:system/lib/liblinearalloc.so \
    vendor/google/gapps/proprietary/system/lib/libmoviemaker-jni.so:system/lib/libmoviemaker-jni.so \
    vendor/google/gapps/proprietary/system/lib/libndk1.so:system/lib/libndk1.so \
    vendor/google/gapps/proprietary/system/lib/libnetjni.so:system/lib/libnetjni.so \
    vendor/google/gapps/proprietary/system/lib/libocrclient.so:system/lib/libocrclient.so \
    vendor/google/gapps/proprietary/system/lib/libpatts_engine_jni_api.so:system/lib/libpatts_engine_jni_api.so \
    vendor/google/gapps/proprietary/system/lib/libplus_jni_v8.so:system/lib/libplus_jni_v8.so \
    vendor/google/gapps/proprietary/system/lib/librectifier-v7a.so:system/lib/librectifier-v7a.so \
    vendor/google/gapps/proprietary/system/lib/librs.antblur_constant.so:system/lib/librs.antblur_constant.so \
    vendor/google/gapps/proprietary/system/lib/librs.antblur_drama.so:system/lib/librs.antblur_drama.so \
    vendor/google/gapps/proprietary/system/lib/librs.antblur.so:system/lib/librs.antblur.so \
    vendor/google/gapps/proprietary/system/lib/librs.drama.so:system/lib/librs.drama.so \
    vendor/google/gapps/proprietary/system/lib/librs.film_base.so:system/lib/librs.film_base.so \
    vendor/google/gapps/proprietary/system/lib/librs.fixedframe.so:system/lib/librs.fixedframe.so \
    vendor/google/gapps/proprietary/system/lib/librs.grey.so:system/lib/librs.grey.so \
    vendor/google/gapps/proprietary/system/lib/librs.image_wrapper.so:system/lib/librs.image_wrapper.so \
    vendor/google/gapps/proprietary/system/lib/librsjni.so:system/lib/librsjni.so \
    vendor/google/gapps/proprietary/system/lib/librs.retrolux.so:system/lib/librs.retrolux.so \
    vendor/google/gapps/proprietary/system/lib/libRSSupport.so:system/lib/libRSSupport.so \
    vendor/google/gapps/proprietary/system/lib/libspeexwrapper.so:system/lib/libspeexwrapper.so \
    vendor/google/gapps/proprietary/system/lib/libvcdecoder_jni.so:system/lib/libvcdecoder_jni.so \
    vendor/google/gapps/proprietary/system/lib/libvideochat_jni.so:system/lib/libvideochat_jni.so \
    vendor/google/gapps/proprietary/system/lib/libvorbisencoder.so:system/lib/libvorbisencoder.so \
    vendor/google/gapps/proprietary/system/lib/libwebp_android.so:system/lib/libwebp_android.so \
    vendor/google/gapps/proprietary/system/lib/libwebrtc_audio_coding.so:system/lib/libwebrtc_audio_coding.so \
    vendor/google/gapps/proprietary/system/lib/libwebrtc_audio_preprocessing.so:system/lib/libwebrtc_audio_preprocessing.so \
    vendor/google/gapps/proprietary/system/lib/libWVphoneAPI.so:system/lib/libWVphoneAPI.so \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/c_fst:system/usr/srec/en-US/c_fst \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/clg:system/usr/srec/en-US/clg \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/commands.abnf:system/usr/srec/en-US/commands.abnf \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/compile_grammar.config:system/usr/srec/en-US/compile_grammar.config \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/contacts.abnf:system/usr/srec/en-US/contacts.abnf \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/dictation.config:system/usr/srec/en-US/dictation.config \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/dict:system/usr/srec/en-US/dict \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/dnn:system/usr/srec/en-US/dnn \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/endpointer_dictation.config:system/usr/srec/en-US/endpointer_dictation.config \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/endpointer_voicesearch.config:system/usr/srec/en-US/endpointer_voicesearch.config \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/ep_acoustic_model:system/usr/srec/en-US/ep_acoustic_model \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/g2p_fst:system/usr/srec/en-US/g2p_fst \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/grammar.config:system/usr/srec/en-US/grammar.config \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/hclg_shotword:system/usr/srec/en-US/hclg_shotword \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/hmmlist:system/usr/srec/en-US/hmmlist \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/hmm_symbols:system/usr/srec/en-US/hmm_symbols \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/hotword_classifier:system/usr/srec/en-US/hotword_classifier \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/hotword.config:system/usr/srec/en-US/hotword.config \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/hotword_normalizer:system/usr/srec/en-US/hotword_normalizer \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/hotword_prompt.txt:system/usr/srec/en-US/hotword_prompt.txt \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/hotword_word_symbols:system/usr/srec/en-US/hotword_word_symbols \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/metadata:system/usr/srec/en-US/metadata \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/normalizer:system/usr/srec/en-US/normalizer \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/norm_fst:system/usr/srec/en-US/norm_fst \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/offensive_word_normalizer:system/usr/srec/en-US/offensive_word_normalizer \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/phonelist:system/usr/srec/en-US/phonelist \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/phone_state_map:system/usr/srec/en-US/phone_state_map \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/rescoring_lm:system/usr/srec/en-US/rescoring_lm \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/wordlist:system/usr/srec/en-US/wordlist \

PRODUCT_PACKAGES += \
    Books \
    CalendarGoogle \
    CalendarProvider \
    ChromeBookmarksSyncAdapter \
    Drive \
    GalleryGoogle \
    GenieWidget \
    Gmail2 \
    GoogleBackupTransport \
    GoogleContactsSyncAdapter \
    GoogleEars \
    GoogleEarth \
    GoogleFeedback \
    GoogleHome \
    GoogleLoginService \
    GooglePartnerSetup \
    GoogleServicesFramework \
    GoogleTTS \
    Hangouts \
    Keep \
    LatinImeGoogle \
    Magazines \
    Maps \
    MediaUploader \
    Music2 \
    OneTimeInitializer \
    Phonesky \
    PlayGames \
    PlusOne \
    PrebuiltGmsCore \
    QuickOffice \
    SetupWizard \
    Street \
    talkback \
    Velvet \
    Videos \
    Wallet \
    YouTube \

